### ISSUE TITLE
Server stuck when Data selction w/ aggegation uses NaN variable

### ISSUE THREAD

**Issue by VectorOhhYeah** [el-meyer/sim_vis_shiny#22]
Leads to Server being stuck (NaN error):
1. check "Use example dataset"
2. check "Do you want to aggregate over a replication run variable?"
3. select an input from "Select the replication run variable", which is not a Number

possible fix:
catch NaN, restrict selection options to Numbers, dont process NaNs

**Comment by majkamichal** [comment]
This issue has been resolved as of 20.11.2022
